### ISSUE TITLE
发票自动识别、入库，避免人工一张一张输入进工具的操作的功能怎么用？

### ISSUE THREAD

**Issue by jasonspeaking7** [NightTeam/invoice-manager#2]
你好，请问这个项目怎么实现发票自动识别的呢？

扫描的发票，能和记录匹配上，从前台查看，或者导出成excle吗？

**Comment by locoz666** [comment]
> 你好，请问这个项目怎么实现发票自动识别的呢？
> 
> 扫描的发票，能和记录匹配上，从前台查看，或者导出成excle吗？

发票自动识别是用的华为云发票识别API做的，运行import_invoice.py就会从指定的导入目录下把发票PDF导入进数据库中，然后就能在Django Admin中直接查看了。没有做导出成Excel表格的功能，如果你需要的话可以自己加一下。

**Comment by jasonspeaking7** [comment]
好的，谢谢这么快就答复。
直接在terminal里运行import_invoice.py,有如下报错。能指导一下要修改哪里吗？谢谢。

Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'simpleui'

**Comment by jasonspeaking7** [comment]
好的，谢谢这么快就答复。那我再研究一下怎么用。
